newsapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.postslist.as_view(), name="posts"),
    path('<slug:slug>/', views.postdetail.as_view(), name="post_detail"),
    path('about/', views.about, name="about"),
]

sportnew24/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS =  (
    (0,"Draft"),
    (1,"Publish"),
    (2,"Delete")
)

# creatin the model class
class posts(models.Model):
    title = models.CharField(max_length = 200, unique =True)
    slug = models.SlugField(max_length = 200, unique = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    created_on = models.DateTimeField(auto_now = True)
    updated_on = models.DateTimeField()
    content = models.TextField()
    metades = models.CharField(max_length=300, default="new post")
    status = models.IntegerField(choices=STATUS, default=0)
    post_images = models.ImageField(upload_to="images")


    class Meta:
        ordering = ['-created_on']
    def __str__(self):
        return self.title
    

newsapp/views.py
from django.shortcuts import render
from .models import posts  
from django.views import generic
from django.views.decorators.http import require_GET

# creating the class based view for post
class postslist(generic.ListView):
    queryset = posts.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog_home.html'
    paginate_by = 6


class postdetail(generic.DetailView):
    model = posts
    template_name = "blog_post.html"


def about(request):
    return render(request, 'about.html')

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    hello this is the about page
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- will be replaced with meta content -->
	{% block metatags %}{% endblock %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
		integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<style>
		html,
		body {
			height: 100%;
		}

		body {
			font-family: sans-serif;
			font-size: 18px;
			background-color: #fdfdfd;
			display: flex;
			flex-direction: column;
		}

		#nofooter {
			flex: 1 0 auto;
		}

		darkbtn {
			color: #66ff99;
		}

		.dark-mode {
			background-color: black;
			color: white;
		}

		#foot {
			flex-shrink: 0;
			font-family: sans-serif;
			background-color: #BDFFD3;
			color: #00308F;
			bottom: 0px;
			width: 100%;
		}

		.card-group,
		.card,
		.card-footer,
		.card-body {
			border: none;
		}
	</style>

</head>

<body>
	<div id="bodydiv">
		<div id="nofooter">
			<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav">
				<div class="container-fluid">
					<img src="/static/icons/logo.png" width="30" height="30" class="d-inline-block rounded align-top"
						alt="logo" loading="lazy">
					GeeksForGeeks</a>
					<div class="nav justify-content-end">
						<div class="d-inline"><a class="nav-link text-black font-weight-bold"
								href="{% url 'posts'%}">Posts</a></div>
					</div>
				</div>
			</nav>
			<!-- will be replaced with post content -->
			{% block content %}
			{% endblock content %}
		</div>
		<footer class="footer" id="foot">
			<div class="container">
				<h5 style="text-align:center;">Enjoy the Blog and Stay Updated</h5>
				<nav class="navbar navbar-expand-lg">
					<div class="container-fluid">





						<p>Copyright © GeeksForGeeks</p>





						<div class="nav justify-content-center" id="navfooter">
							<span><a class="nav-link text-black font-weight-bold" href="#">Feed</a></span>
						</div>
					</div>
				</nav>
			</div>
		</footer>
	</div>
</body>

</html>

templates/blog_post.html
{% extends 'blog_base.html' %}
{% load static %}
{% block metatags %}
<title>{{ object.title }}</title>
<meta name="description" content="{{ object.metades}}" />
<meta property="og:title" content="{{ object.title }}">
<meta property="og:site_name" content="GeeksForGeeks">
<meta property="og:url" content="{% url 'post_detail' object.slug %}">
<meta property="og:description" content="{{ object.metades }}">
<meta property="og:type" content="article">
{% endblock %}
{% block content %}

<div class="page-wrapper">

    <!-- start of breadcumb-section -->
    <div class="bg-[url(../images/page-title.jpg)] bg-no-repeat bg-center bg-cover min-h-[400px] relative flex justify-center flex-col z-10
        sm:min-h-[250px] before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-[#232f4b]
        before:-z-10 before:opacity-70 md:mt-3">
        <div class="wraper">
            <div class="grid grid-cols-12">
                <div class="col-span-12">
                    <div class="text-center">
                        <h2 class="text-6xl text-white mt-[-10px] mb-[20px] sm:text-3xl sm:mb-[10px]">Blog Single
                        </h2>
                        <ul class="">
                            <li
                                class="inline-block px-[5px] text-white relative text-xl font-heading-font sm:text-lg after:content-['/'] after:left-[7px]">
                                <a href="index.html">Home</a>
                            </li>
                            <li
                                class="text-[#cbd4fd] inline-block px-[5px]  relative text-xl font-heading-font sm:text-lg ">
                                <span>Blog</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end of wpo-breadcumb-section-->

    <!-- start wpo-blog-pg-section -->
    <div class="py-[60px] md:py-[40px]">
        <!-- start of hero -->
        <div class="wraper">
            <div class="grid grid-cols-12 gap-x-4">
                <div class="col-span-1 md:col-span-12 "></div>
                <div class="col-span-10 md:col-span-12">
                    <div class="md:mt-[70px]">
                        <img class="w-full" src="{{ object.post_images.url }}" alt>
                        <div class="overflow-hidden my-[35px]">
                            <ul>
                                <li
                                    class="text-[14px] font-medium uppercase float-left col:float-none col:block col:ml-[0px] col:mb-[5px] text-[#687693]">
                                    <i class="relative top-0 mr-[3px] text-[15px] text-[#687693]  fi flaticon-user"></i>
                                    By <a class="text-[#687693] transition-all hover:text-[#3756f7]" href="#">{{ object.author }} </a>
                                </li>
                                <li
                                    class="text-[14px] font-medium uppercase float-left col:float-none col:block col:ml-[0px] col:mb-[5px] text-[#687693] ml-[20px] pl-[20px] relative before:absolute before:left-0 before:top-[50%] before:w-[7px] before:h-[7px] before:rounded-[50%] before:content-[''] before:translate before:-translate-y-1/2 before:bg-[#3756f7] z-10 before:-z-10">

                                <li
                                    class="text-[14px] font-medium uppercase float-left col:float-none col:block col:ml-[0px] col:mb-[5px] text-[#687693] ml-[20px] pl-[20px] relative before:absolute before:left-0 before:top-[50%] before:w-[7px] before:h-[7px] before:rounded-[50%] before:content-[''] before:translate before:-translate-y-1/2 before:bg-[#3756f7] z-10 before:-z-10">
                                    <i
                                        class="relative top-0 mr-[3px] text-[15px] text-[#687693]  fi flaticon-calendar-1"></i>{{ object.created_on }}
                                </li>
                            </ul>
                        </div>
                        <h3 class="text-[34px] md:text-[25px] sm:text-[22px] text-[#0a272c]  leading-[40px] mb-[20px]">
                            {% block title %}
                            {{ object.title }}
                            {% endblock title %}
                        </h3>
                        <p class="text-[#687693] leading-[24px] text-[16px] mb-[20px]">
                            {{ object.content }}
                        </p>

                    </div>

                    <!-- end tag-share -->
                    <div class="mt-[30px] pb-[30px] text-white sm:mb-[40px]">
                        <div class="flex items-center">
                            <span class="font-heading-font text-[#0a272c] font-semibold inline-block pr-[15px]
                                uppercase">Share:
                            </span>
                            <ul class="inline-block">
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">facebook</a>
                                </li>
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">twitter</a>
                                </li>
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">linkedin</a>
                                </li>
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">pinterest</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- end tag-share -->


                </div>
                <div class="col-span-1 md:col-span-12 "></div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

templates/blog_post_head.html
{% extends 'blog_base.html' %}
{% load static %}
{% block metatags %}
<title>{{ object.title }}</title>
<meta name="description" content="{{ object.metades}}" />
<meta property="og:title" content="{{ object.title }}">
<meta property="og:site_name" content="GeeksForGeeks">
<meta property="og:url" content="{% url 'post_detail' object.slug %}">
<meta property="og:description" content="{{ object.metades }}">
<meta property="og:type" content="article">
{% endblock %}
{% block content %}

<div class="page-wrapper">

    <!-- start of breadcumb-section -->
    <div class="bg-[url(../images/page-title.jpg)] bg-no-repeat bg-center bg-cover min-h-[400px] relative flex justify-center flex-col z-10
        sm:min-h-[250px] before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-[#232f4b]
        before:-z-10 before:opacity-70 md:mt-3">
        <div class="wraper">
            <div class="grid grid-cols-12">
                <div class="col-span-12">
                    <div class="text-center">
                        <h2 class="text-6xl text-white mt-[-10px] mb-[20px] sm:text-3xl sm:mb-[10px]">Blog Single
                        </h2>
                        <ul class="">
                            <li
                                class="inline-block px-[5px] text-white relative text-xl font-heading-font sm:text-lg after:content-['/'] after:left-[7px]">
                                <a href="index.html">Home</a>
                            </li>
                            <li
                                class="text-[#cbd4fd] inline-block px-[5px]  relative text-xl font-heading-font sm:text-lg ">
                                <span>Blog</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end of wpo-breadcumb-section-->

    <!-- start wpo-blog-pg-section -->
    <div class="py-[60px] md:py-[40px]">
        <!-- start of hero -->
        <div class="wraper">
            <div class="grid grid-cols-12 gap-x-4">
                <div class="col-span-1 md:col-span-12 "></div>
                <div class="col-span-10 md:col-span-12">
                    <div class="md:mt-[70px]">
                        <img class="w-full" src="{{ head_post.post_images.url }}" alt>
                        <div class="overflow-hidden my-[35px]">
                            <ul>
                                <li
                                    class="text-[14px] font-medium uppercase float-left col:float-none col:block col:ml-[0px] col:mb-[5px] text-[#687693]">
                                    <i class="relative top-0 mr-[3px] text-[15px] text-[#687693]  fi flaticon-user"></i>
                                    By <a class="text-[#687693] transition-all hover:text-[#3756f7]" href="#">
                                        <!-- {{ head_object.author }} -->
                                     </a>
                                </li>
                                <li
                                    class="text-[14px] font-medium uppercase float-left col:float-none col:block col:ml-[0px] col:mb-[5px] text-[#687693] ml-[20px] pl-[20px] relative before:absolute before:left-0 before:top-[50%] before:w-[7px] before:h-[7px] before:rounded-[50%] before:content-[''] before:translate before:-translate-y-1/2 before:bg-[#3756f7] z-10 before:-z-10">

                                <li
                                    class="text-[14px] font-medium uppercase float-left col:float-none col:block col:ml-[0px] col:mb-[5px] text-[#687693] ml-[20px] pl-[20px] relative before:absolute before:left-0 before:top-[50%] before:w-[7px] before:h-[7px] before:rounded-[50%] before:content-[''] before:translate before:-translate-y-1/2 before:bg-[#3756f7] z-10 before:-z-10">
                                    <i
                                        class="relative top-0 mr-[3px] text-[15px] text-[#687693]  fi flaticon-calendar-1"></i>
                                        <!-- {{ head_object.created_on }} -->
                                </li>
                            </ul>
                        </div>
                        <h3 class="text-[34px] md:text-[25px] sm:text-[22px] text-[#0a272c]  leading-[40px] mb-[20px]">
                            <!-- {% block title %}
                            {{ head_object.title }}
                            {% endblock title %} -->
                        </h3>
                        <p class="text-[#687693] leading-[24px] text-[16px] mb-[20px]">
                            {{ head_object.content }}
                        </p>

                    </div>

                    <!-- end tag-share -->
                    <div class="mt-[30px] pb-[30px] text-white sm:mb-[40px]">
                        <div class="flex items-center">
                            <span class="font-heading-font text-[#0a272c] font-semibold inline-block pr-[15px]
                                uppercase">Share:
                            </span>
                            <ul class="inline-block">
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">facebook</a>
                                </li>
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">twitter</a>
                                </li>
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">linkedin</a>
                                </li>
                                <li class="float-left ml-[10px] sm:m-[2px] sm:ml-0"><a href="#"
                                        class="inline-block text-[15px] capitalize text-[#6e6e6e] underline font-normal transition-all hover:text-[#3756f7]">pinterest</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- end tag-share -->


                </div>
                <div class="col-span-1 md:col-span-12 "></div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block metatags %}
<title>Home | GeeksForGeeks</title>
<meta name="description" content="A destination for Learning">
<meta property="og:title" content="GeeksForGeeks">
<meta property="og:site_name" content="GeeksForGeeks">
<meta property="og:url" content="https://GeeksForGeeks.org">
<meta property="og:description" content="A destination for Learning">
<meta property="og:type" content="website">
{% endblock %}
{% block content %}

<style type="text/css">
	body {
	font-family: 'Raleway', sans-serif;}
	.head_text {
		color: white;
	}
.h1, h4 {
font-family: 'Raleway', sans-serif;
}
#mainhome {
text-align: center; }
</style>
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;">
	<div class="container">
	<p class="h1"> Welcome to <strong>GeeksForGeeks</strong></p>





				</div>
</header>

<div class="container">
	<div class="row">
		<div class="col-md-8 mt-3 left">
			{% for post in posts_list %}
			<div class="shadow-none card mb-4" id="newsfeed">
				<div class="card-body">
					<h3 class="card-title">{{ post.title }}</h3>
					<div class="card ">
						<img src="{{ post.post_images.url }}" alt="image" style="max-width: 300px;" >
					</div>
					<p class="card-text text-muted h6"><span>{{ post.author.first_name }} {{ post.author.last_name }}</span> | {{ post.created_on}} </p>





					<p class="card-text">{{post.metades }} </p>





<span><a href="{% url 'post_detail' post.slug %}" class="btn btn-outline-primary">Read More →</a></span>
<span><a href="{% url 'post_detail' post.slug %}" class="btn btn-outline-success">sure AMPpage</a></span>
	
		</div>
			</div>
			{% endfor %}
		</div>
</div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation container"></nav>
<ul class="pagination justify-content-center">
	{% if page_obj.has_previous %}
	<li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li>
	{% endif %}
	{% if page_obj.has_next %}
	<li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li>

	{% endif %}
</ul>
{% endif %}
{%endblock%}

templates/post.html
{% extends 'base.html' %}
{% block metatags %}
<title>{{ object.title }}</title>
<meta name="description" content="{{ object.metades}}" />
<meta property="og:title" content="{{ object.title }}">
<meta property="og:site_name" content="GeeksForGeeks">
<meta property="og:url" content="{% url 'post_detail' object.slug %}">
<meta property="og:description" content="{{ object.metades }}">
<meta property="og:type" content="article">
{% endblock %}
{% block content %}

<style type="text/css">
	#container img {
		border-radius: 29px;
		width: 100%;
		height: 360px;
		opacity: 0.7;
		align-content: center;
	}

	#container img {
		opacity: 1.0;
	}

	a {
		text-align: center;
		text-decoration: none;
	}
	.box_img {
		height: 90px;
		width: 90px;
	}
</style>

<div class="container">
	<div class="row">
		
		<div class="col-md-6 left">
			<h1 class="card-title">
				{% block title %} 
				{{ object.title }} 
				{% endblock title %}
			</h1>
			<p class=" text-muted">{{ object.author }} {{ object.author.last_name }} |{{ object.created_on }}
			</p>
			<div class="card">
				<img src="{{ object.post_images.url }}" alt="image" style="max-width: 300px;" >
			</div>




			<p class="card-text">{{ object.content | safe }}</p>





		</div>
	</div>
</div>
{% endblock content %}